# Generated by Django 3.1.7 on 2021-04-18 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_comment_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='st_address',
            new_name='address',
        ),
    ]
