# Generated by Django 3.1.7 on 2021-04-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_address_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address2',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
