# Generated by Django 3.1.7 on 2021-04-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_address_address2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='home_address',
        ),
    ]
